---
AWSTemplateFormatVersion: '2010-09-09'
Description: Content Mover & BC Stack
Parameters:
  Domain:
    Description: Domain name
    Type: String
  DbMasterUsername:
    Description: User name of the master user
    Type: String
  DbMasterPassword:
    Description: Password for the master user
    Type: String
    NoEcho: true
  Encryption:
    Description: 'Encryption method of S3 Bucket'
    Type: String
    AllowedValues:
    - 'Default'
    - 'KMS'
Resources:
  NetworkingStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://prosperoware-cloudformation-templates.s3.amazonaws.com/nested_stacks/networking.yml
      TimeoutInMinutes: '5'
  IAMRolesStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://prosperoware-cloudformation-templates.s3.amazonaws.com/nested_stacks/roles.yml
      TimeoutInMinutes: '2'
  ResourcesStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://prosperoware-cloudformation-templates.s3.amazonaws.com/nested_stacks/resources.yml
      TimeoutInMinutes: '15'
      Parameters:
        Domain: !Ref Domain
        DbMasterUsername: !Ref DbMasterUsername
        DbMasterPassword: !Ref DbMasterPassword
        Encryption: !Ref Encryption
        VPC: !GetAtt  NetworkingStack.Outputs.VPC
        PrivateSubnetOne: !GetAtt NetworkingStack.Outputs.PrivateSubnetOne
        PrivateSubnetTwo: !GetAtt NetworkingStack.Outputs.PrivateSubnetTwo
        RDSSecurityGroupId: !GetAtt NetworkingStack.Outputs.RDSSecurityGroup
        LambdaSecurityGroup: !GetAtt NetworkingStack.Outputs.LambdaSecurityGroup
        CodeBuildRole: !GetAtt  IAMRolesStack.Outputs.CodeBuildRole