---
AWSTemplateFormatVersion: '2010-09-09'
Description: Content Mover & BC Stack
Metadata: 
  AWS::CloudFormation::Interface: 
    ParameterGroups: 
      - 
        Label: 
          default: "Instance Configuration"
        Parameters: 
          - InstanceName
      - 
        Label: 
          default: "RDS Instance Configuration"
        Parameters: 
          - DBMasterUsername
          - DBMasterPassword
      -
        Label:
          default: "S3 Bucket Configuration"
        Parameters:
          - Encryption
    ParameterLabels: 
      InstanceName: 
        default: "Instance Name"
      DBMasterUsername:
        default: "Database Master Username"
      DBMasterPassword:
        default: "Database Master Password"
      Encryption:
        default: "S3 Encryption"
Parameters:
  InstanceName:
    Description: Your instance name (e.g. prosperoware)
    Type: String
  DBMasterUsername:
    Description: Master username for your RDS Instance.
    Type: String
  DBMasterPassword:
    Description: Master password for your RDS instance.
    Type: String
    NoEcho: true
  Encryption:
    Type: String
    AllowedValues:
    - 'Default Encryption (SSE-S3)'
    - 'AWS Key Management Service key (SSE-KMS)'
Resources:
  NetworkingStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://prosperoware-cloudformation-templates.s3.amazonaws.com/nested_stacks/networking.yml
      TimeoutInMinutes: '5'
  IAMRolesStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://prosperoware-cloudformation-templates.s3.amazonaws.com/nested_stacks/roles.yml
      TimeoutInMinutes: '2'
  ResourcesStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://prosperoware-cloudformation-templates.s3.amazonaws.com/nested_stacks/resources.yml
      TimeoutInMinutes: '15'
      Parameters:
        Domain: !Ref InstanceName
        DbMasterUsername: !Ref DBMasterUsername
        DbMasterPassword: !Ref DBMasterPassword
        Encryption: !Ref Encryption
        VPC: !GetAtt  NetworkingStack.Outputs.VPC
        PrivateSubnetOne: !GetAtt NetworkingStack.Outputs.PrivateSubnetOne
        PrivateSubnetTwo: !GetAtt NetworkingStack.Outputs.PrivateSubnetTwo
        RDSSecurityGroupId: !GetAtt NetworkingStack.Outputs.RDSSecurityGroup
        LambdaSecurityGroup: !GetAtt NetworkingStack.Outputs.LambdaSecurityGroup
        CodeBuildRole: !GetAtt  IAMRolesStack.Outputs.CodeBuildRole